name: mlk-frontend-deploy
on: 
  push:
    branches: [master]
jobs:
  deploy-job:
    env:
      GITHUB_TOKEN: ${{ secrets.PRODUCT_DEPLOY_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v0.1.2
        with: 
          host: ${{secrets.MLK_HOST}}
          key: ${{secrets.MLK_KEY}}
          username: ${{secrets.MLK_USER}}

          script: |
            mkdir -r test
            cd test
            git clone https://dexitional:$GITHUB_TOKEN@github.com/dexitional/ums-ehub.git ./test
            echo 'Deployment Succesful to Digital Ocean' 
              
            